=== zsmartsystems/com.zsmartsystems.zigbee/com.zsmartsystems.zigbee.autocode/src/main/resources/zigbee-description.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="cluster">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="name" />
				<xs:element type="xs:string" name="description" maxOccurs="unbounded" minOccurs="0" />
				<xs:element name="command" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="name" />
							<xs:element type="xs:string" name="description" maxOccurs="unbounded" minOccurs="0" />
							<xs:element name="field" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="name" />
										<xs:element type="xs:string" name="description" maxOccurs="unbounded" minOccurs="0" />
										<xs:element name="conditional" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:string" name="field" />
													<xs:element type="xs:string" name="operator" />
													<xs:element type="xs:string" name="value" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="sizer" maxOccurs="1" minOccurs="0" />
										<xs:element type="xs:string" name="format" minOccurs="0" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="type" use="optional" />
									<xs:attribute type="xs:string" name="class" use="optional" />
									<xs:attribute type="xs:boolean" name="completeOnZero" use="optional" />
								</xs:complexType>
							</xs:element>
							<xs:element name="response" minOccurs="0">
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="code" use="optional" />
						<xs:attribute type="xs:string" name="source" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element name="attribute" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="name" />
							<xs:element type="xs:string" name="description" maxOccurs="unbounded" minOccurs="0" />
						</xs:sequence>
						<xs:attribute type="xs:string" name="code" use="optional" />
						<xs:attribute type="xs:string" name="type" use="optional" />
						<xs:attribute type="xs:string" name="class" use="optional" />
						<xs:attribute type="xs:string" name="side" use="optional" />
						<xs:attribute type="xs:string" name="minimum" use="optional" />
						<xs:attribute type="xs:string" name="maximum" use="optional" />
						<xs:attribute type="xs:string" name="optional" use="optional" />
						<xs:attribute type="xs:string" name="writable" use="optional" />
						<xs:attribute type="xs:string" name="reportable" use="optional" />
						<xs:attribute type="xs:integer" name="arraystart" use="optional" />
						<xs:attribute type="xs:integer" name="arraycount" use="optional" />
						<xs:attribute type="xs:integer" name="arraystep" use="optional" />
						<xs:attribute type="xs:string" name="default" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element name="constant" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="name" />
							<xs:element type="xs:string" name="description" maxOccurs="unbounded" minOccurs="0" />
							<xs:element name="value" maxOccurs="unbounded" minOccurs="1">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="code" use="required" />
											<xs:attribute type="xs:string" name="name" use="required" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="type" />
						<xs:attribute type="xs:string" name="class" />
					</xs:complexType>
				</xs:element>
				<xs:element name="struct" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="name" minOccurs="0" />
							<xs:element name="field" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="name" />
										<xs:element type="xs:string" name="description" minOccurs="0" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="type" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="class" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element name="scenes" maxOccurs="1" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="extensionfield" maxOccurs="1" minOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="attribute" maxOccurs="unbounded" minOccurs="1"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="class" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute type="xs:string" name="code" />
		</xs:complexType>
	</xs:element>
	<xs:element name="zigbee">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="constant" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="name"/>
              <xs:element type="xs:string" name="description" minOccurs="0"/>
              <xs:element name="value" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="scope" use="optional" />
                      <xs:attribute type="xs:string" name="code" use="required"/>
                      <xs:attribute type="xs:string" name="name" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="class" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== zsmartsystems/com.zsmartsystems.zigbee/com.zsmartsystems.zigbee.autocode/src/main/resources/000C_AnalogInputBasic.xml
<cluster xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="zigbee-description.xsd" code="0x000C">
    <name>Analog Input (Basic)</name>
    <description>The Analog Input (Basic) cluster provides an interface for reading the value of an analog measurement and accessing various characteristics of that measurement. The cluster is typically used to implement a sensor that measures an analog physical quantity.</description>

    <attribute code="0x001C" type="CHARACTER_STRING" side="server" optional="true" writable="true" reportable="false">
        <name>Description</name>
        <description>The Description attribute, of type Character string, MAY be used to hold a description of the usage of the input, output or value, as appropriate to the cluster. The character set used SHALL be ASCII, and the at- tribute SHALL contain a maximum of 16 characters, which SHALL be printable but are otherwise unrestricted.</description>
    </attribute>
    <attribute code="0x0041" type="FLOAT_32_BIT" side="server" optional="true" writable="true" reportable="false">
        <name>Max Present Value</name>
        <description>The MaxPresentValue attribute, of type Single precision, indicates the highest value that can be reliably obtained for the PresentValue attribute of an Analog Input cluster, or which can reliably be used for the PresentValue attribute of an Analog Output or Analog Value cluster.</description>
    </attribute>
    <attribute code="0x0045" type="FLOAT_32_BIT" side="server" optional="true" writable="true" reportable="false">
        <name>Min Present Value</name>
        <description>The MinPresentValue attribute, of type Single precision, indicates the lowest value that can be reliably ob- tained for the PresentValue attribute of an Analog Input cluster, or which can reliably be used for the PresentValue attribute of an Analog Output or Analog Value cluster.</description>
    </attribute>
    <attribute code="0x0051" type="BOOLEAN" side="server" optional="true" writable="true" reportable="false">
        <name>Out Of Service</name>
        <description></description>
    </attribute>
    <attribute code="0x0055" type="FLOAT_32_BIT" side="server" optional="true" writable="true" reportable="false">
        <name>Present Value</name>
        <description>The PresentValue attribute indicates the current value of the input, output or value, as appropriate  for the cluster. For Analog clusters it is of type single precision, for Binary clusters it is of type  Boolean, and for multistate clusters it is of type Unsigned 16-bit integer. The PresentValue attribute of an input cluster SHALL be writable when OutOfService is TRUE. When the PriorityArray attribute is implemented, writing to PresentValue SHALL be equivalent to writing to element 16 of PriorityArray, i.e., with a priority of 16.</description>
    </attribute>
    <attribute code="0x0067" type="ENUMERATION_8_BIT" side="server" class="AnalogInputReliabilityEnum" optional="true" writable="true" reportable="false">
        <name>Reliability</name>
        <description>The Reliability attribute, of type 8-bit enumeration, provides an indication of whether the PresentValueor the operation of the physical input, output or value in question (as appropriate for the cluster) is &#8220;reliable&#8221; as far as can be determined and, if not, why not. The Reliability attribute MAY have any of the following values:</description>
        <description>NO-FAULT-DETECTED (0) OVER-RANGE (2) UNDER-RANGE (3) OPEN-LOOP (4) SHORTED-LOOP (5) UNRELIABLE-OTHER (7) PROCESS-ERROR (8) MULTI-STATE-FAULT (9) CONFIGURATION-ERROR (10)</description>
    </attribute>
    <attribute code="0x006A" type="FLOAT_32_BIT" side="server" optional="true" writable="true" reportable="false">
        <name>Resolution</name>
        <description>This attribute, of type Single precision, indicates the smallest recognizable change to PresentValue.</description>
    </attribute>
    <attribute code="0x006F" type="BITMAP_8_BIT" side="server" class="AnalogInputStatusFlagsBitmap" optional="true" writable="true" reportable="false">
        <name>Status Flags</name>
        <description>This attribute, of type bitmap, represents four Boolean flags that indicate the general &#8220;health&#8221; of the analog sensor. Three of the flags are associated with the values of other optional attributes of this cluster. A more detailed status could be determined by reading the optional attributes (if supported) that are linked to these flags. The relationship between individual flags is not defined.</description>
        <description>The four flags are Bit 0 = IN_ALARM, Bit 1 = FAULT, Bit 2 = OVERRIDDEN, Bit 3 = OUT OF SERVICE</description>
        <description>where:</description>
        <description>IN_ALARM -Logical FALSE (0) if the EventStateattribute has a value of NORMAL, otherwise logical TRUE (1). This bit is always 0 unless the cluster implementing the EventState attribute is implemented on the same endpoint.</description>
        <description>FAULT -Logical TRUE (1) if the Reliability attribute is present and does not have a value of NO FAULT DETECTED, otherwise logical FALSE (0).</description>
        <description>OVERRIDDEN -Logical TRUE (1) if the cluster has been overridden by some  mechanism local to the device. Otherwise, the value is logical FALSE (0). In this context, for an input cluster, &#8220;overridden&#8221; is taken to mean that the PresentValue and Reliability(optional) attributes are no longer tracking changes to the physical input. For an Output cluster, &#8220;overridden&#8221; is taken to mean that the physical output is no longer tracking changes to the PresentValue attribute and the Reliability attribute is no longer a reflection of the physical output. For a Value cluster, &#8220;overridden&#8221; is taken to mean that the PresentValue attribute is not writeable.</description>
        <description>OUT OF SERVICE -Logical TRUE (1) if the OutOfService attribute has a value of TRUE, otherwise logical FALSE (0).</description>
    </attribute>
    <attribute code="0x0075" type="ENUMERATION_32_BIT" side="server" optional="true" writable="true" reportable="false">
        <name>Engineering Units</name>
        <description>The EngineeringUnits attribute indicates the physical units associated with the value of the PresentValue attribute of an Analog cluster.</description>
        <description>Values 0x0000 to 0x00fe are reserved for the list of engineering units with corresponding values specified in Clause 21 of the BACnet standard. 0x00ff represents 'other'. Values 0x0100 to 0xffff are available for proprietary use.</description>
        <description>If the ApplicationType attribute is implemented, and is set to a value with a defined physical unit, the physical unit defined in ApplicationType takes priority over EngineeringUnits.</description>
        <description>This attribute is defined to be Read Only, but a vendor can decide to allow this to be written to if ApplicationType is also supported. If this attribute is written to, how the device handles invalid units (e.g., changing Deg F to Cubic Feet per Minute), any local display or other vendor-specific operation (upon the change) is a local matter.</description>
    </attribute>
    <attribute code="0x0100" type="SIGNED_32_BIT_INTEGER" side="server" optional="true" writable="true" reportable="false">
        <name>Application Type</name>
        <description>The ApplicationType attribute is an unsigned 32 bit integer that indicates the specific application usage for this cluster. (Note: This attribute has no BACnet equivalent). ApplicationType is subdivided into Group, Type and an Index number, as follows.</description>
        <description>Group = Bits 24-31 An indication of the cluster this attribute is part of.</description>
        <description>Type = Bits 16-23 For Analog clusters, the physical quantity that the Present Value attribute of the cluster represents. For Binary and Multistate clusters, the application usage domain.</description>
        <description>Index = Bits 0-15The specific application usage of the cluster.</description>
    </attribute>

    <constant class="AnalogInputReliabilityEnum">
        <name>Reliability</name>
        <value code="0x00" name="No - Fault - Detected">
        </value>
        <value code="0x02" name="Over - Range">
        </value>
        <value code="0x03" name="Under - Range">
        </value>
        <value code="0x04" name="Open - Loop">
        </value>
        <value code="0x05" name="Shorted - Loop">
        </value>
        <value code="0x07" name="Unreliable - Other">
        </value>
        <value code="0x08" name="Process - Error">
        </value>
        <value code="0x09" name="Multi - State - Fault">
        </value>
        <value code="0x0A" name="Configuration - Error">
        </value>
    </constant>
    <constant class="AnalogInputStatusFlagsBitmap">
        <name>Status Flags</name>
        <value code="0x01" name="In_Alarm">
        </value>
        <value code="0x02" name="Fault">
        </value>
        <value code="0x04" name="Overridden">
        </value>
        <value code="0x08" name="Out Of Service">
        </value>
    </constant>

</cluster>

=== zsmartsystems/com.zsmartsystems.zigbee/com.zsmartsystems.zigbee/src/main/xml/zcl/0014_MultistateValueBasic.xml
<cluster xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="zigbee-description.xsd" code="0x0014">
    <name>Multistate Value (Basic)</name>
    <description>The Multistate Value (Basic) cluster provides an interface for setting a multistate value, typically used as a control system parameter, and accessing characteristics of that value.</description>
    <attribute code="0x000E" type="CHARACTER_STRING" side="server" optional="true" writable="true" reportable="false">
        <name>State Text</name>
        <description>This  attribute, of type Array of Character strings, holds descriptions of all possible states of a multistate PresentValue.  The number of descriptions matches the number of states defined in the NumberOfStates property. The PresentValue, interpreted as an integer, serves as an index into the array. If the size of this array is changed, the NumberOfStates property SHALL also be changed to the same value. The character set used SHALL be ASCII, and the attribute SHALL contain a maximum of 16 characters, which SHALL be printable but are otherwise unrestricted.</description>
    </attribute>
    <attribute code="0x001C" type="CHARACTER_STRING" side="server" optional="true" writable="true" reportable="false">
        <name>Description</name>
        <description>The Description attribute, of type Character string, MAY be used to hold a description of the usage of the input, output or value, as appropriate to the cluster. The character set used SHALL be ASCII, and the attribute SHALL contain a maximum of 16 characters, which SHALL be printable but are otherwise unrestricted.</description>
    </attribute>
    <attribute code="0x004A" type="UNSIGNED_16_BIT_INTEGER" side="server" optional="false" writable="true" reportable="false">
        <name>Number Of States</name>
        <description>This attribute, of type Unsigned 16-bit integer, defines the number of states that a multistate PresentValue MAY have. The NumberOfStates property SHALL always have a value greater than zero. If the value of this property is changed, the size of the StateText array, if present, SHALL also be changed to the same value. The states are numbered consecutively, starting with 1.</description>
    </attribute>
    <attribute code="0x0051" type="BOOLEAN" side="server" optional="false" writable="true" reportable="false">
        <name>Out Of Service</name>
        <description>The OutOfService attribute, of type Boolean, indicates whether (TRUE) or not (FALSE) the physical input, output or value that the cluster represents is not in service. For an Input cluster, when OutOfService is TRUE the PresentValue attribute is decoupled from the physical input and  will not track changes to the  physical input. For an Output cluster, when OutOfService is TRUE the PresentValue attribute is decoupled from the physical output, so changes to PresentValue will not affect the physical output. For a Value cluster, when OutOfService is TRUE the PresentValue attribute MAY be written to freely by software local to the device that the cluster resides on.</description>
    </attribute>
    <attribute code="0x0055" type="UNSIGNED_16_BIT_INTEGER" side="server" optional="false" writable="true" reportable="false">
        <name>Present Value</name>
        <description>The PresentValue attribute indicates the current value of the input, output or value, as appropriate for the cluster. For Analog clusters it is of type single precision, for Binary clusters it is of type  Boolean, and for multistate clusters it is of type Unsigned 16-bit integer. The PresentValue attribute of an input cluster SHALL be writable when OutOfService is TRUE. When the PriorityArray attribute is implemented, writing to PresentValue SHALL be equivalent to writing to element 16 of PriorityArray, i.e., with a priority of 16.</description>
    </attribute>
    <attribute code="0x0067" type="ENUMERATION_8_BIT" side="server" class="MultistateValueReliabilityEnum" optional="true" writable="true" reportable="false">
        <name>Reliability</name>
        <description>The Reliability attribute, of type 8-bit enumeration, provides an indication of whether the PresentValueor the operation of the physical input, output or value in question (as appropriate for the cluster) is &#8220;reliable&#8221; as far as can be determined and, if not, why not. The Reliability attribute MAY have any of the following values:</description>
        <description>NO-FAULT-DETECTED (0) OVER-RANGE (2) UNDER-RANGE (3) OPEN-LOOP (4) SHORTED-LOOP (5) UNRELIABLE-OTHER (7) PROCESS-ERROR (8) MULTI-STATE-FAULT (9) CONFIGURATION-ERROR (10)</description>
    </attribute>
    <attribute code="0x0068" type="UNSIGNED_16_BIT_INTEGER" side="server" optional="true" writable="true" reportable="false">
        <name>Relinquish Default</name>
        <description>The RelinquishDefault attribute is the default value to be used for the PresentValue attribute when all elements of the PriorityArray attribute are marked as invalid.</description>
    </attribute>
    <attribute code="0x006F" type="BITMAP_8_BIT" side="server" class="MultistateValueStatusFlagsBitmap" optional="false" writable="false" reportable="false">
        <name>Status Flags</name>
        <description>This attribute, of type bitmap, represents four Boolean flags that indicate the general &#8220;health&#8221; of the analog sensor. Three of the flags are associated with the values of other optional attributes of this cluster. A more detailed status could be determined by reading the optional attributes (if supported) that are linked to these flags. The relationship between individual flags is not defined.</description>
        <description>The four flags are Bit 0 = IN_ALARM, Bit 1 = FAULT, Bit 2 = OVERRIDDEN, Bit 3 = OUT OF SERVICE</description>
        <description>where:</description>
        <description>IN_ALARM -Logical FALSE (0) if the EventStateattribute has a value of NORMAL, otherwise logical TRUE (1). This bit is always 0 unless the cluster implementing the EventState attribute is implemented on the same endpoint.</description>
        <description>FAULT -Logical TRUE (1) if the Reliability attribute is present and does not have a value of NO FAULT DETECTED, otherwise logical FALSE (0).</description>
        <description>OVERRIDDEN -Logical TRUE (1) if the cluster has been overridden by some  mechanism local to the device. Otherwise, the value is logical FALSE (0). In this context, for an input cluster, &#8220;overridden&#8221; is taken to mean that the PresentValue and Reliability(optional) attributes are no longer tracking changes to the physical input. For an Output cluster, &#8220;overridden&#8221; is taken to mean that the physical output is no longer tracking changes to the PresentValue attribute and the Reliability attribute is no longer a reflection of the physical output. For a Value cluster, &#8220;overridden&#8221; is taken to mean that the PresentValue attribute is not writeable.</description>
        <description>OUT OF SERVICE -Logical TRUE (1) if the OutOfService attribute has a value of TRUE, otherwise logical FALSE (0).</description>
    </attribute>
    <attribute code="0x0100" type="SIGNED_32_BIT_INTEGER" side="server" optional="true" writable="false" reportable="false">
        <name>Application Type</name>
        <description>The ApplicationType attribute is an unsigned 32 bit integer that indicates the specific application usage for this cluster. (Note: This attribute has no BACnet equivalent). ApplicationType is subdivided into Group, Type and an Index number, as follows.</description>
        <description>Group = Bits 24 -31 An indication of the cluster this attribute is part of.</description>
        <description>Type = Bits 16 -23 For Analog clusters, the physical quantity that the Present Value attribute of the cluster represents. For Binary and Multistate clusters, the application usage domain.</description>
        <description>Index = Bits 0 -15The specific application usage of the cluster.</description>
    </attribute>

    <constant class="MultistateValueReliabilityEnum">
        <name>Reliability</name>
        <value code="0x00" name="No - Fault - Detected">
        </value>
        <value code="0x02" name="Over - Range">
        </value>
        <value code="0x03" name="Under - Range">
        </value>
        <value code="0x04" name="Open - Loop">
        </value>
        <value code="0x05" name="Shorted - Loop">
        </value>
        <value code="0x07" name="Unreliable - Other">
        </value>
        <value code="0x08" name="Process - Error">
        </value>
        <value code="0x09" name="Multi - State - Fault">
        </value>
        <value code="0x0A" name="Configuration - Error">
        </value>
    </constant>
    <constant class="MultistateValueStatusFlagsBitmap">
        <name>Status Flags</name>
        <value code="0x01" name="In_Alarm">
        </value>
        <value code="0x02" name="Fault">
        </value>
        <value code="0x04" name="Overridden">
        </value>
        <value code="0x08" name="Out Of Service">
        </value>
    </constant>
</cluster>
