=== zsmartsystems/com.zsmartsystems.zigbee/com.zsmartsystems.zigbee.autocode/src/main/resources/zigbee-description.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="cluster">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="name" />
				<xs:element type="xs:string" name="description" maxOccurs="unbounded" minOccurs="0" />
				<xs:element name="command" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="name" />
							<xs:element type="xs:string" name="description" maxOccurs="unbounded" minOccurs="0" />
							<xs:element name="field" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="name" />
										<xs:element type="xs:string" name="description" maxOccurs="unbounded" minOccurs="0" />
										<xs:element name="conditional" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:string" name="field" />
													<xs:element type="xs:string" name="operator" />
													<xs:element type="xs:string" name="value" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="sizer" maxOccurs="1" minOccurs="0" />
										<xs:element type="xs:string" name="format" minOccurs="0" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="type" use="optional" />
									<xs:attribute type="xs:string" name="class" use="optional" />
									<xs:attribute type="xs:boolean" name="completeOnZero" use="optional" />
								</xs:complexType>
							</xs:element>
							<xs:element name="response" minOccurs="0">
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="code" use="optional" />
						<xs:attribute type="xs:string" name="source" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element name="attribute" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="name" />
							<xs:element type="xs:string" name="description" maxOccurs="unbounded" minOccurs="0" />
						</xs:sequence>
						<xs:attribute type="xs:string" name="code" use="optional" />
						<xs:attribute type="xs:string" name="type" use="optional" />
						<xs:attribute type="xs:string" name="class" use="optional" />
						<xs:attribute type="xs:string" name="side" use="optional" />
						<xs:attribute type="xs:string" name="minimum" use="optional" />
						<xs:attribute type="xs:string" name="maximum" use="optional" />
						<xs:attribute type="xs:string" name="optional" use="optional" />
						<xs:attribute type="xs:string" name="writable" use="optional" />
						<xs:attribute type="xs:string" name="reportable" use="optional" />
						<xs:attribute type="xs:integer" name="arraystart" use="optional" />
						<xs:attribute type="xs:integer" name="arraycount" use="optional" />
						<xs:attribute type="xs:integer" name="arraystep" use="optional" />
						<xs:attribute type="xs:string" name="default" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element name="constant" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="name" />
							<xs:element type="xs:string" name="description" maxOccurs="unbounded" minOccurs="0" />
							<xs:element name="value" maxOccurs="unbounded" minOccurs="1">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="code" use="required" />
											<xs:attribute type="xs:string" name="name" use="required" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="type" />
						<xs:attribute type="xs:string" name="class" />
					</xs:complexType>
				</xs:element>
				<xs:element name="struct" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="name" minOccurs="0" />
							<xs:element name="field" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="name" />
										<xs:element type="xs:string" name="description" minOccurs="0" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="type" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="class" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element name="scenes" maxOccurs="1" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="extensionfield" maxOccurs="1" minOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="attribute" maxOccurs="unbounded" minOccurs="1"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="class" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute type="xs:string" name="code" />
		</xs:complexType>
	</xs:element>
	<xs:element name="zigbee">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="constant" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="name"/>
              <xs:element type="xs:string" name="description" minOccurs="0"/>
              <xs:element name="value" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="scope" use="optional" />
                      <xs:attribute type="xs:string" name="code" use="required"/>
                      <xs:attribute type="xs:string" name="name" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="class" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== zsmartsystems/com.zsmartsystems.zigbee/com.zsmartsystems.zigbee.autocode/src/main/resources/0301_BallastConfiguration.xml
<cluster xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="zigbee-description.xsd" code="0x0301">
    <name>Ballast Configuration</name>
    <description></description>
    <attribute code="0x0000" type="UNSIGNED_8_BIT_INTEGER" side="server" optional="true" writable="false" reportable="false" minimum="0x00" maximum="0xFE" default="0x01">
        <name>Physical Min Level</name>
        <description>The PhysicalMinLevel attribute is 8 bits in length and specifies the minimum light output95 the ballast can achieve. This attribute SHALL be specified in the range 0x01 to 0xfe, and specifies the light output of the ballast according to the dimming light curve</description>
    </attribute>
    <attribute code="0x0001" type="UNSIGNED_8_BIT_INTEGER" side="server" optional="true" writable="false" reportable="false" minimum="0x00" maximum="0xFE" default="0xFE">
        <name>Physical Max Level</name>
        <description>The PhysicalMaxLevel attribute is 8 bits in length and specifies the maximum light output96 the ballast can achieve according to the dimming light curve</description>
    </attribute>
    <attribute code="0x0002" type="BITMAP_8_BIT" side="server" optional="false" writable="false" reportable="false" minimum="0x00" maximum="0x03" default="0x00">
        <name>Ballast Status</name>
        <description>The BallastStatus attribute is 8 bits in length and specifies the activity status of the ballast functions. The usage of the bits is specified in Table 5-31. Where a function is active, the corresponding bit SHALL be set to 1. Where a function is not active, the corresponding bit SHALL be set to 0.</description>
    </attribute>

    <attribute code="0x0010" type="UNSIGNED_8_BIT_INTEGER" side="server" optional="true" writable="true" reportable="false" minimum="0x00" maximum="0xFE" default="0x01">
        <name>Min Level</name>
        <description>The MinLevel attribute is 8 bits in length and specifies the light output of the ballast according to the dimming light curve when the Level Control Cluster’s CurrentLevel attribute equals to 0x01 (1) (and the On/Off Clusters’s OnOff attribute equals to 0x01)</description>
        <description>The value of this attribute SHALL be both greater than or equal to PhysicalMinLevel and less than or equal to MaxLevel. If an attempt is made to set this attribute to a level where these conditions are not met, a default response command SHALL be returned with status code set to INVALID_VALUE, and the level SHALL not be set.</description>
    </attribute>
    <attribute code="0x0011" type="UNSIGNED_8_BIT_INTEGER" side="server" optional="true" writable="true" reportable="false" minimum="0x00" maximum="0xFE" default="0xFE">
        <name>Max Level</name>
        <description>The MaxLevel attribute is 8 bits in length and specifies the light output of the ballast according to the dimming light curve when the Level Control Cluster’s CurrentLevel attribute equals to 0xfe (254) (and the On/Off Cluster’s OnOff attribute equals to 0x01)</description>
        <description>The value of this attribute SHALL be both less than or equal to PhysicalMaxLevel and greater than or equal to MinLevel. If an attempt is made to set this attribute to a level where these conditions are not met, a default response command SHALL be returned with status code set to INVALID_VALUE, and the level SHALL not be set.</description>
    </attribute>
    <attribute code="0x0012" type="UNSIGNED_8_BIT_INTEGER" side="server" optional="true" writable="true" reportable="false" minimum="0x00" maximum="0xFE" default="0xFE">
        <name>Power On Level</name>
        <description>Deprecated</description>
    </attribute>
    <attribute code="0x0013" type="UNSIGNED_16_BIT_INTEGER" side="server" optional="true" writable="true" reportable="false" minimum="0x0000" maximum="0xFFFE" default="0x00">
        <name>Power On Fade Time</name>
        <description>Deprecated</description>
    </attribute>
    <attribute code="0x0014" type="UNSIGNED_8_BIT_INTEGER" side="server" optional="true" writable="true" reportable="false" minimum="0x00" maximum="0xFE" default="0x00">
        <name>Intrinsic Ballast Factor</name>
        <description>The IntrinsicBallastFactor attribute is 8 bits in length and specifies as a percentage the ballast factor of the ballast/lamp combination, prior to any adjustment.</description>
        <description>A value of 0xff indicates in invalid value.</description>
    </attribute>
    <attribute code="0x0015" type="UNSIGNED_8_BIT_INTEGER" side="server" optional="true" writable="true" reportable="false" minimum="0x64" maximum="0xFF" default="0xFF">
        <name>Ballast Factor Adjustment</name>
        <description>The BallastFactorAdjustment attribute is 8 bits in length and specifies the multiplication factor, as a percentage, to be applied to the configured light output of the lamps. A typical usage of this mechanism is to compensate for reduction in efficiency over the lifetime of a lamp.</description>
        <description>The range for this attribute is manufacturer dependent. If an attempt is made to set this attribute to a level that cannot be supported, a default response command SHALL be returned with status code set to INVALID_VALUE, and the level SHALL not be set. The value 0xff indicates that ballast factor scaling is not in use.</description>
    </attribute>
    <attribute code="0x0020" type="UNSIGNED_8_BIT_INTEGER" side="server" optional="true" writable="true" reportable="false" minimum="0x00" maximum="0xFE" default="0x00">
        <name>Lamp Quantity</name>
        <description>The LampQuantity attribute is 8 bits in length and specifies the number of lamps connected to this ballast. (Note: this number does not take into account whether lamps are actually in their sockets or not).</description>
   </attribute>
    <attribute code="0x0030" type="CHARACTER_STRING" side="server" optional="true" writable="true" reportable="false">
        <name>Lamp Type</name>
        <description>The LampType attribute is a character string of up to 16 bytes in length. It specifies the type of lamps (including their wattage) connected to the ballast.</description>
    </attribute>
    <attribute code="0x0031" type="CHARACTER_STRING" side="server" optional="true" writable="true" reportable="false">
        <name>Lamp Manufacturer</name>
        <description>The LampManufacturer attribute is a character string of up to 16 bytes in length. It specifies the name of the manufacturer of the currently connected lamps.</description>
    </attribute>
    <attribute code="0x0032" type="SIGNED_24_BIT_INTEGER" side="server" optional="true" writable="true" reportable="false" minimum="0x000000" maximum="0xFFFFFE" default="0xFFFFFF">
        <name>Lamp Rated Hours</name>
        <description>The LampRatedHours attribute is 24 bits in length and specifies the number of hours of use the lamps are rated for by the manufacturer.</description>
        <description>A value of 0xffffff indicates an invalid or unknown time.</description>
    </attribute>
    <attribute code="0x0033" type="SIGNED_24_BIT_INTEGER" side="server" optional="true" writable="true" reportable="false" minimum="0x000000" maximum="0xFFFFFE" default="0x000000">
        <name>Lamp Burn Hours</name>
        <description>The LampBurnHours attribute is 24 bits in length and specifies the length of time, in hours, the currently connected lamps have been operated, cumulative since the last re-lamping. Burn hours SHALL not be accumulated if the lamps are off.</description>
        <description>This attribute SHOULD be reset to zero (e.g., remotely) when the lamp(s) are changed. If partially used lamps are connected, LampBurnHours SHOULD be updated to reflect the burn hours of the lamps.</description>
        <description>A value of 0xffffff indicates an invalid or unknown time.</description>
    </attribute>
    <attribute code="0x0034" type="BITMAP_8_BIT" side="server" optional="true" writable="true" reportable="false" minimum="0x00" maximum="0x01" default="0x00">
        <name>Lamp Alarm Mode</name>
        <description>The LampsAlarmMode attribute is 8 bits in length and specifies which attributes MAY cause an alarm notification to be generated. A ‘1’ in each bit position causes its associated attribute to be able to generate an alarm. (Note: All alarms are also logged in the alarm table – see Alarms cluster).</description>
    </attribute>
    <attribute code="0x0033" type="SIGNED_24_BIT_INTEGER" side="server" optional="true" writable="true" reportable="false" minimum="0x000000" maximum="0xFFFFFE" default="0xFFFFFF">
        <name>Lamp Burn Hours Trip Point</name>
        <description>The LampBurnHoursTripPoint attribute is 24 bits in length and specifies the number of hours the LampBurnHours attribute MAY reach before an alarm is generated.</description>
        <description>If the Alarms cluster is not present on the same device this attribute is not used and thus MAY be omitted</description>
        <description>The Alarm Code field included in the generated alarm SHALL be 0x01.</description>
        <description>If this attribute takes the value 0xffffff then this alarm SHALL not be generated.</description>
    </attribute>

</cluster>

=== zsmartsystems/com.zsmartsystems.zigbee/com.zsmartsystems.zigbee.autocode/src/main/resources/0402_TemperatureMeasurement.xml
<cluster xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="zigbee-description.xsd" code="0x0402">
    <name>Temperature Measurement</name>
    <description>The server cluster provides an interface to temperature measurement functionality, including configuration and provision of notifications of temperature measurements.</description>
    <attribute code="0x0000" type="SIGNED_16_BIT_INTEGER" side="server" optional="false" writable="false" reportable="true" default="0x0000">
        <name>Measured Value</name>
        <description>MeasuredValue represents the temperature in degrees Celsius as follows:- MeasuredValue = 100 x temperature in degrees Celsius.</description>
        <description>Where -273.15&#176;C &lt;= temperature &lt;= 327.67 &#186;C, corresponding to a</description>
        <description>MeasuredValue in the range 0x954d to 0x7fff. The maximum resolution this format allows is 0.01 &#186;C.</description>
        <description>A MeasuredValue of 0x8000 indicates that the temperature measurement is invalid.</description>
        <description>MeasuredValue is updated continuously as new measurements are made.</description>
    </attribute>
    <attribute code="0x0001" type="SIGNED_16_BIT_INTEGER" side="server" optional="false" writable="false" reportable="false" minimum="0x954D" maximum="0x7FFE">
        <name>Min Measured Value</name>
        <description>The MinMeasuredValue attribute indicates the minimum value of MeasuredValue that is capable of being measured. A MinMeasuredValue of 0x8000 indicates that the minimum value is unknown.</description>
    </attribute>
    <attribute code="0x0002" type="SIGNED_16_BIT_INTEGER" side="server" optional="false" writable="false" reportable="false" minimum="0x954E" maximum="0x7FFF">
        <name>Max Measured Value</name>
        <description>The MaxMeasuredValue attribute indicates the maximum value of MeasuredValue that is capable of being measured.</description>
        <description>MaxMeasuredValue shall be greater than MinMeasuredValue.</description>
        <description>MinMeasuredValue and MaxMeasuredValue define the range of the sensor.</description>
        <description>A MaxMeasuredValue of 0x8000 indicates that the maximum value is unknown.</description>
    </attribute>
    <attribute code="0x0003" type="UNSIGNED_16_BIT_INTEGER" side="server" optional="true" writable="false" reportable="true" minimum="0x0000" maximum="0x0800">
        <name>Tolerance</name>
        <description>The Tolerance attribute indicates the magnitude of the possible error that is associated with MeasuredValue . The true value is located in the range (MeasuredValue &#8211; Tolerance) to (MeasuredValue + Tolerance).</description>
    </attribute>

</cluster>

=== zsmartsystems/com.zsmartsystems.zigbee/com.zsmartsystems.zigbee/src/main/xml/zcl/0401_IlluminanceLevelSensing.xml
<cluster xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="zigbee-description.xsd" code="0x0401">
    <name>Illuminance Level Sensing</name>
    <description>The cluster provides an interface to illuminance level sensing functionality, including configuration and provision of notifications of whether the illuminance is within, above or below a target band.</description>
    <attribute code="0x0000" type="ENUMERATION_8_BIT" side="server" optional="false" writable="false" reportable="true">
        <name>Level Status</name>
        <description>The LevelStatus attribute indicates whether the measured illuminance is above, below, or within a band around IlluminanceTargetLevel .</description>
    </attribute>
    <attribute code="0x0001" type="ENUMERATION_8_BIT" side="server" optional="true" writable="false" reportable="false">
        <name>Light Sensor Type</name>
        <description>The LightSensorType attribute specifies the electronic type of the light sensor.</description>
    </attribute>
    <attribute code="0x0010" type="UNSIGNED_16_BIT_INTEGER" side="server" optional="true" writable="false" reportable="false" minimum="0x0000" maximum="0xFFFE">
        <name>Illuminance Target Level</name>
        <description>The IlluminanceTargetLevel attribute specifies the target illuminance level. This target level is taken as the centre of a &apos;dead band&apos;, which must be sufficient in width, with hysteresis bands at both top and bottom, to provide reliable notifications without &apos;chatter&apos;. Such a dead band and hysteresis bands must be provided by any implementation of this cluster. (N.B. Manufacturer specific attributes may be provided to configure these).</description>
        <description>IlluminanceTargetLevel represents illuminance in Lux (symbol lx) as follows:</description>
        <description>IlluminanceTargetLevel = 10,000 x log10 Illuminance</description>
        <description>Where 1 lx &lt;= Illuminance &lt;=3.576 Mlx, corresponding to a MeasuredValue in the range 0 to 0xfffe.</description>
        <description>A value of 0xffff indicates that this attribute is not valid.</description>
    </attribute>

</cluster>

=== zsmartsystems/com.zsmartsystems.zigbee/com.zsmartsystems.zigbee/src/main/xml/zcl/0004_Groups.xml
<cluster xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="zigbee-description.xsd" code="0x0004">
    <name>Groups</name>
    <description>The ZigBee specification provides the capability for group addressing. That is, any endpoint on any device may be assigned to one or more groups, each labeled with a 16-bit identifier (0x0001 &#8211; 0xfff7), which acts for all intents and purposes like a network address. Once a group is established, frames, sent using the APSDE-DATA.request primitive and having a DstAddrMode of 0x01, denoting group addressing, will be delivered to every endpoint assigned to the group address named in the DstAddr parameter of the outgoing APSDE-DATA.request primitive on every device in the network for which there are such endpoints.</description>
    <description>Management of group membership on each device and endpoint is implemented by the APS, but the over-the-air messages that allow for remote management and commissioning of groups are defined here in the cluster library on the theory that, while the basic group addressing facilities are integral to the operation of the stack, not every device will need or want to implement this management cluster. Furthermore, the placement of the management commands here allows developers of proprietary profiles to avoid implementing the library cluster but still exploit group addressing</description>
    <description>In order to ensure that only authorized devices are able to set up groups (particularly if application link keys are to be used) the following approach SHOULD be employed. The security Permissions Configuration Table provides a mechanism by which certain commands can be restricted to specified authorized devices. Configuration of groups via the Groups cluster SHOULD use the ApplicationSettings permissions entry of this table to specify from which devices group configuration commands MAY be received, and whether a link key is required.</description>
    <command code="0x00" source="client">
        <name>Add Group Command</name>
        <description>The Add Group command allows the sending device to add group membership in a particular group for one or more endpoints on the receiving device.</description>
        <field type="UNSIGNED_16_BIT_INTEGER">
            <name>Group ID</name>
        </field>
        <field type="CHARACTER_STRING">
            <name>Group Name</name>
        </field>
    </command>
    <command code="0x01" source="client">
        <name>View Group Command</name>
        <description>The view group command allows the sending device to request that the receiving entity or entities respond with a view group response command containing the application name string for a particular group.</description>
        <field type="UNSIGNED_16_BIT_INTEGER">
            <name>Group ID</name>
        </field>
    </command>
    <command code="0x02" source="client">
        <name>Get Group Membership Command</name>
        <description>The get group membership command allows the sending device to inquire about the group membership of the receiving device and endpoint in a number of ways.</description>
        <field type="UNSIGNED_8_BIT_INTEGER">
            <name>Group Count</name>
        </field>
        <field type="N_X_UNSIGNED_16_BIT_INTEGER">
            <name>Group List</name>
        </field>
    </command>
    <command code="0x03" source="client">
        <name>Remove Group Command</name>
        <description>The remove group command allows the sender to request that the receiving entity or entities remove their membership, if any, in a particular group.</description>
        <field type="UNSIGNED_16_BIT_INTEGER">
            <name>Group ID</name>
        </field>
    </command>
    <command code="0x04" source="client">
        <name>Remove All Groups Command</name>
        <description>The remove all groups command allows the sending device to direct the receiving entity or entities to remove all group associations.</description>
    </command>
    <command code="0x05" source="client">
        <name>Add Group If Identifying Command</name>
        <description>The add group if identifying command allows the sending device to add group membership in a particular group for one or more endpoints on the receiving device, on condition that it is identifying itself. Identifying functionality is controlled using the identify cluster.</description>
        <field type="UNSIGNED_16_BIT_INTEGER">
            <name>Group ID</name>
        </field>
        <field type="CHARACTER_STRING">
            <name>Group Name</name>
        </field>
    </command>
    <command code="0x00" source="server">
        <name>Add Group Response</name>
        <description>The add group response is sent by the groups cluster server in response to an add group command.</description>
        <field type="ENUMERATION_8_BIT">
            <name>Status</name>
        </field>
        <field type="UNSIGNED_16_BIT_INTEGER">
            <name>Group ID</name>
        </field>
    </command>
    <command code="0x01" source="server">
        <name>View Group Response</name>
        <description>The view group response command is sent by the groups cluster server in response to a view group command.</description>
        <field type="ENUMERATION_8_BIT">
            <name>Status</name>
        </field>
        <field type="UNSIGNED_16_BIT_INTEGER">
            <name>Group ID</name>
        </field>
        <field type="CHARACTER_STRING">
            <name>Group Name</name>
        </field>
    </command>
    <command code="0x02" source="server">
        <name>Get Group Membership Response</name>
        <description>The get group membership response command is sent by the groups cluster server in response to a get group membership command.</description>
        <field type="UNSIGNED_8_BIT_INTEGER">
            <name>Capacity</name>
        </field>
        <field type="UNSIGNED_8_BIT_INTEGER">
            <name>Group Count</name>
        </field>
        <field type="N_X_UNSIGNED_16_BIT_INTEGER">
            <name>Group List</name>
        </field>
    </command>
    <command code="0x03" source="server">
        <name>Remove Group Response</name>
        <description>The remove group response command is generated by an application entity in response to the receipt of a remove group command.</description>
        <field type="ENUMERATION_8_BIT">
            <name>Status</name>
        </field>
        <field type="UNSIGNED_16_BIT_INTEGER">
            <name>Group ID</name>
        </field>
    </command>
    
    <attribute code="0x0000" type="BITMAP_8_BIT" side="server" optional="false" writable="false" reportable="false">
        <name>Name Support</name>
        <description>The most significant bit of the NameSupport attribute indicates whether or not group names are supported. A value of 1 indicates that they are supported, and a value of 0 indicates that they are not supported.</description>
    </attribute>
    
</cluster>
