=== zsmartsystems/com.zsmartsystems.zigbee/com.zsmartsystems.zigbee.autocode/src/main/resources/zigbee-description.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="cluster">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="name" />
				<xs:element type="xs:string" name="description" maxOccurs="unbounded" minOccurs="0" />
				<xs:element name="command" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="name" />
							<xs:element type="xs:string" name="description" maxOccurs="unbounded" minOccurs="0" />
							<xs:element name="field" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="name" />
										<xs:element type="xs:string" name="description" maxOccurs="unbounded" minOccurs="0" />
										<xs:element name="conditional" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:string" name="field" />
													<xs:element type="xs:string" name="operator" />
													<xs:element type="xs:string" name="value" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="sizer" maxOccurs="1" minOccurs="0" />
										<xs:element type="xs:string" name="format" minOccurs="0" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="type" use="optional" />
									<xs:attribute type="xs:string" name="class" use="optional" />
									<xs:attribute type="xs:boolean" name="completeOnZero" use="optional" />
								</xs:complexType>
							</xs:element>
							<xs:element name="response" minOccurs="0">
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="code" use="optional" />
						<xs:attribute type="xs:string" name="source" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element name="attribute" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="name" />
							<xs:element type="xs:string" name="description" maxOccurs="unbounded" minOccurs="0" />
						</xs:sequence>
						<xs:attribute type="xs:string" name="code" use="optional" />
						<xs:attribute type="xs:string" name="type" use="optional" />
						<xs:attribute type="xs:string" name="class" use="optional" />
						<xs:attribute type="xs:string" name="side" use="optional" />
						<xs:attribute type="xs:string" name="minimum" use="optional" />
						<xs:attribute type="xs:string" name="maximum" use="optional" />
						<xs:attribute type="xs:string" name="optional" use="optional" />
						<xs:attribute type="xs:string" name="writable" use="optional" />
						<xs:attribute type="xs:string" name="reportable" use="optional" />
						<xs:attribute type="xs:integer" name="arraystart" use="optional" />
						<xs:attribute type="xs:integer" name="arraycount" use="optional" />
						<xs:attribute type="xs:integer" name="arraystep" use="optional" />
						<xs:attribute type="xs:string" name="default" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element name="constant" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="name" />
							<xs:element type="xs:string" name="description" maxOccurs="unbounded" minOccurs="0" />
							<xs:element name="value" maxOccurs="unbounded" minOccurs="1">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="code" use="required" />
											<xs:attribute type="xs:string" name="name" use="required" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="type" />
						<xs:attribute type="xs:string" name="class" />
					</xs:complexType>
				</xs:element>
				<xs:element name="struct" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="name" minOccurs="0" />
							<xs:element name="field" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="name" />
										<xs:element type="xs:string" name="description" minOccurs="0" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="type" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="class" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element name="scenes" maxOccurs="1" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="extensionfield" maxOccurs="1" minOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="attribute" maxOccurs="unbounded" minOccurs="1"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="class" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute type="xs:string" name="code" />
		</xs:complexType>
	</xs:element>
	<xs:element name="zigbee">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="constant" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="name"/>
              <xs:element type="xs:string" name="description" minOccurs="0"/>
              <xs:element name="value" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="scope" use="optional" />
                      <xs:attribute type="xs:string" name="code" use="required"/>
                      <xs:attribute type="xs:string" name="name" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="class" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== zsmartsystems/com.zsmartsystems.zigbee/com.zsmartsystems.zigbee/src/main/xml/zcl/0502_IasWd.xml
<cluster xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="zigbee-description.xsd" code="0x0502">
    <name>IAS WD</name>
    <description>The IAS WD cluster provides an interface to the functionality of any Warning Device equipment of the IAS system. Using this cluster, a ZigBee enabled CIE device can access a ZigBee enabled IAS WD device and issue alarm warning indications (siren, strobe lighting, etc.) when a system alarm condition is detected.</description>
    <command code="0x00" source="client">
        <name>Start Warning Command</name>
        <description>This command starts the WD operation. The WD alerts the surrounding area by audible (siren) and visual (strobe) signals. &lt;br&gt; A Start Warning command shall always terminate the effect of any previous command that is still current.</description>
        <field type="DATA_8_BIT" class="WarningInfoEnum">
            <name>Header</name>
        </field>
        <field type="UNSIGNED_16_BIT_INTEGER">
            <name>Warning Duration</name>
        </field>
    </command>
    <command code="0x01" source="client">
        <name>Squawk</name>
        <description>This command uses the WD capabilities to emit a quick audible/visible pulse called a "squawk". The squawk command has no effect if the WD is currently active (warning in progress).</description>
        <field type="BITMAP_8_BIT" class="SquawkInfoBitmap">
            <name>Squawk Info</name>
        </field>
    </command>

    <attribute code="0x0000" type="UNSIGNED_16_BIT_INTEGER" side="server" optional="false" writable="true" reportable="false" minimum="0x0000" maximum="0xFFFE" default="0x00F0">
        <name>Max Duration</name>
        <description>The MaxDuration attribute specifies the maximum time in seconds that the siren will sound continuously, regardless of start/stop commands.</description>
    </attribute>

    <constant type="BITMAP_8_BIT" class="SquawkInfoBitmap">
        <name>Squawk Info</name>
        <value code="0x03" name="Level">
        </value>
        <value code="0x08" name="Strobe">
        </value>
        <value code="0xF0" name="Mode">
        </value>
    </constant>

</cluster>

=== zsmartsystems/com.zsmartsystems.zigbee/com.zsmartsystems.zigbee.autocode/src/main/resources/0407_LeafWetness.xml
<cluster xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="zigbee-description.xsd" code="0x0407">
    <name>Leaf Wetness Measurement</name>
    <description>The server cluster provides an interface to read the percentage of water on the leaves of plants.</description>
    <attribute code="0x0000" type="UNSIGNED_16_BIT_INTEGER" side="server" optional="false" writable="false" reportable="true">
        <name>Measured Value</name>
        <description>MeasuredValue represents the leaf wetness in % as follows:-</description>
        <description>MeasuredValue = 100 x Leaf Wetness</description>
        <description>Where 0% &lt;= leaf wetness &lt;= 100%, corresponding to a MeasuredValue in the range 0 to 0x2710.</description>
        <description>The maximum resolution this format allows is 0.01%.</description>
        <description>A MeasuredValue of 0xffff indicates that the measurement is invalid.</description>
        <description>MeasuredValue is updated continuously as new measurements are made.</description>
    </attribute>
    <attribute code="0x0001" type="UNSIGNED_16_BIT_INTEGER" side="server" optional="false" writable="false" reportable="false" minimum="0x0000" maximum="0x270F">
        <name>Min Measured Value</name>
        <description>The MinMeasuredValue attribute indicates the minimum value of MeasuredValue that can be measured. A value of 0xffff means this attribute is not defined</description>
    </attribute>
    <attribute code="0x0002" type="UNSIGNED_16_BIT_INTEGER" side="server" optional="false" writable="false" reportable="false" minimum="0x0001" maximum="0x2710">
        <name>Max Measured Value</name>
        <description>The MaxMeasuredValue attribute indicates the maximum value of MeasuredValue that can be measured. A value of 0xffff means this attribute is not defined.</description>
        <description>MaxMeasuredValue shall be greater than MinMeasuredValue.</description>
        <description>MinMeasuredValue and MaxMeasuredValue define the range of the sensor.</description>
    </attribute>
    <attribute code="0x0003" type="UNSIGNED_16_BIT_INTEGER" side="server" optional="true" writable="false" reportable="true" minimum="0x0000" maximum="0x0800">
        <name>Tolerance</name>
        <description>The Tolerance attribute indicates the magnitude of the possible error that is associated with MeasuredValue . The true value is located in the range (MeasuredValue &#8211; Tolerance) to (MeasuredValue + Tolerance).</description>
    </attribute>

</cluster>

=== zsmartsystems/com.zsmartsystems.zigbee/com.zsmartsystems.zigbee.autocode/src/main/resources/0B01_MeterIdentification.xml
<cluster xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="zigbee-description.xsd" code="0x0B01">
    <name>Meter Identification</name>
    <description>This cluster provides attributes and commands for determining advanced information about utility metering device.</description>

    <attribute code="0x0000" type="CHARACTER_STRING" side="server" optional="false" writable="false" reportable="false">
        <name>Company Name</name>
        <description>This attribute defines the meter manufacturer name, decided by manufacturer.</description>
    </attribute>
    <attribute code="0x0001" type="UNSIGNED_16_BIT_INTEGER" side="server" optional="false" writable="false" reportable="false" minimum="0x0000" maximum="0xFFFF">
        <name>Meter Type ID</name>
        <description>This attribute defines the Meter installation features, decided by manufacturer.</description>
    </attribute>
    <attribute code="0x0004" type="UNSIGNED_16_BIT_INTEGER" side="server" optional="false" writable="false" reportable="false" minimum="0x0000" maximum="0xFFFF">
        <name>Data Quality ID</name>
        <description>This attribute defines the Meter Simple Metering information certification type, decided by manufacturer.</description>
    </attribute>
    <attribute code="0x0005" type="CHARACTER_STRING" side="server" optional="true" writable="true" reportable="false">
        <name>Customer Name</name>
    </attribute>
    <attribute code="0x0006" type="CHARACTER_STRING" side="server" optional="true" writable="false" reportable="false">
        <name>Model</name>
        <description>This attribute defines the meter model name, decided by manufacturer.</description>
    </attribute>
    <attribute code="0x0007" type="CHARACTER_STRING" side="server" optional="true" writable="false" reportable="false">
        <name>Part Number</name>
        <description>This attribute defines the meter part number, decided by manufacturer.</description>
    </attribute>
    <attribute code="0x0008" type="CHARACTER_STRING" side="server" optional="true" writable="false" reportable="false">
        <name>Product Revision</name>
        <description>This attribute defines the meter revision code, decided by manufacturer.</description>
    </attribute>
    <attribute code="0x000A" type="CHARACTER_STRING" side="server" optional="true" writable="false" reportable="false">
        <name>Software Revision</name>
        <description>This attribute defines the meter software revision code, decided by manufacturer.</description>
    </attribute>
    <attribute code="0x000B" type="CHARACTER_STRING" side="server" optional="true" writable="false" reportable="false">
        <name>Utility Name</name>
    </attribute>
    <attribute code="0x000C" type="CHARACTER_STRING" side="server" optional="false" writable="false" reportable="false">
        <name>POD</name>
        <description>This attribute is the unique identification ID of the premise connection point. It is also a contractual information known by the clients and indicated in the bill.</description>
    </attribute>
    <attribute code="0x000D" type="SIGNED_24_BIT_INTEGER" side="server" optional="false" writable="false" reportable="false" minimum="0x000000" maximum="0xFFFFFF">
        <name>Available Power</name>
        <description>This attribute represents the InstantaneousDemand that can be distributed to the customer (e.g., 3.3KW power) without any risk of overload. The Available Power SHALL use the same formatting conventions as the one used in the simple metering cluster formatting attribute set for the InstantaneousDemand attribute, i.e., the UnitOfMeasure and DemandFormatting.</description>
    </attribute>
    <attribute code="0x000E" type="SIGNED_24_BIT_INTEGER" side="server" optional="false" writable="false" reportable="false" minimum="0x000000" maximum="0xFFFFFF">
        <name>Power Threshold</name>
        <description>This attribute represents a threshold of InstantaneousDemand distributed to the customer (e.g., 4.191KW) that will lead to an imminent risk of overload. The PowerThreshold SHALL use the same formatting conventions as the one used in the AvailablePower attributes and therefore in the simple metering cluster formatting attribute set for the InstantaneousDemand attribute, i.e., the UnitOfMeasure and DemandFormatting.</description>
    </attribute>

    <constant class="MeterTypeEnum">
        <name>Meter Type</name>
        <value code="0x0000" name="Utility Primary Meter">
        </value>
        <value code="0x0001" name="Utility Production Meter">
        </value>
        <value code="0x0002" name="Utility Secondary Meter">
        </value>
        <value code="0x0100" name="Private Primary Meter">
        </value>
        <value code="0x0101" name="Private Production Meter">
        </value>
        <value code="0x0102" name="Private Secondary Meters">
        </value>
        <value code="0x0110" name="Generic Meter">
        </value>
    </constant>

    <constant class="DataQualityEnum">
        <name>Data Quality</name>
        <value code="0x0000" name="All Data Certified">
        </value>
        <value code="0x0001" name="Only Instantaneous Power not Certified">
        </value>
        <value code="0x0002" name="Only Cumulated Consumption not Certified">
        </value>
        <value code="0x0003" name="Not Certified data">
        </value>
    </constant>
</cluster>

=== zsmartsystems/com.zsmartsystems.zigbee/com.zsmartsystems.zigbee.autocode/src/main/resources/0008_LevelControl.xml
<cluster xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="zigbee-description.xsd" code="0x0008">
    <name>Level Control</name>
    <description>This cluster provides an interface for controlling a characteristic of a device that can be set to a level, for example the brightness of a light, the degree of closure of a door, or the power output of a heater.</description>
    <description>For many applications, a close relationship between this cluster and the OnOff cluster is needed. This section describes the dependencies that are required when an endpoint that implements the Level Control server cluster also implements the On/Off server cluster.</description>
    <description>The OnOff attribute of the On/Off cluster and the CurrentLevel attribute of the Level Control cluster are intrinsically independent variables, as they are on different clusters. However, when both clusters are implemented on the same endpoint, dependencies MAY be introduced between them. Facilities are provided to introduce dependencies if required.</description>
    <description>There are two sets of commands provided in the Level Control cluster. These are identical, except that the first set (Move to Level, Move and Step) SHALL NOT affect the OnOff attribute, whereas the second set ('with On/Off' variants) SHALL.</description>
    <command code="0x00" source="client">
        <name>Move To Level Command</name>
        <description>On receipt of this command, a device SHALL move from its current level to the value given in the Level field. The meaning of &#8216;level&#8217; is device dependent &#8211;e.g., for a light it MAY mean brightness level.The movement SHALL be as continuous as technically practical, i.e., not a step function, and the time taken to move to the new level SHALL be equal to the value of the Transition time field, in tenths of a second, or as close to this as the device is able.If the Transition time field takes the value 0xffff then the time taken to move to the new level SHALL instead be determined by the OnOffTransitionTimeattribute. If OnOffTransitionTime, which is an optional attribute, is not present, the device SHALL move to its new level as fast as it is able.</description>
        <field type="UNSIGNED_8_BIT_INTEGER">
            <name>Level</name>
        </field>
        <field type="UNSIGNED_16_BIT_INTEGER">
            <name>Transition Time</name>
        </field>
    </command>
    <command code="0x01" source="client">
        <name>Move Command</name>
        <field type="ENUMERATION_8_BIT">
            <name>Move Mode</name>
        </field>
        <field type="UNSIGNED_8_BIT_INTEGER">
            <name>Rate</name>
        </field>
    </command>
    <command code="0x02" source="client">
        <name>Step Command</name>
        <field type="ENUMERATION_8_BIT">
            <name>Step Mode</name>
        </field>
        <field type="UNSIGNED_8_BIT_INTEGER">
            <name>Step Size</name>
        </field>
        <field type="UNSIGNED_16_BIT_INTEGER">
            <name>Transition Time</name>
        </field>
    </command>
    <command code="0x03" source="client">
        <name>Stop Command</name>
        <description>Upon receipt of this command, any Move to Level, Move or Step command (and their 'with On/Off' variants) currently in process SHALL be terminated. The value of CurrentLevel SHALL be left at its value upon receipt of the Stop command, and RemainingTime SHALL be set to zero.</description>
    </command>
    <command code="0x04" source="client">
        <name>Move To Level (with On/Off) Command</name>
        <description>On receipt of this command, a device SHALL move from its current level to the value given in the Level field. The meaning of &#8216;level&#8217; is device dependent &#8211;e.g., for a light it MAY mean brightness level.The movement SHALL be as continuous as technically practical, i.e., not a step function, and the time taken to move to the new level SHALL be equal to the value of the Transition time field, in tenths of a second, or as close to this as the device is able.If the Transition time field takes the value 0xffff then the time taken to move to the new level SHALL instead be determined by the OnOffTransitionTimeattribute. If OnOffTransitionTime, which is an optional attribute, is not present, the device SHALL move to its new level as fast as it is able.</description>
        <field type="UNSIGNED_8_BIT_INTEGER">
            <name>Level</name>
        </field>
        <field type="UNSIGNED_16_BIT_INTEGER">
            <name>Transition Time</name>
        </field>
    </command>
    <command code="0x05" source="client">
        <name>Move (with On/Off) Command</name>
        <field type="ENUMERATION_8_BIT">
            <name>Move Mode</name>
        </field>
        <field type="UNSIGNED_8_BIT_INTEGER">
            <name>Rate</name>
        </field>
    </command>
    <command code="0x06" source="client">
        <name>Step (with On/Off) Command</name>
        <field type="ENUMERATION_8_BIT">
            <name>Step Mode</name>
        </field>
        <field type="UNSIGNED_8_BIT_INTEGER">
            <name>Step Size</name>
        </field>
        <field type="UNSIGNED_16_BIT_INTEGER">
            <name>Transition Time</name>
        </field>
    </command>
    <command code="0x07" source="client">
        <name>Stop 2 Command</name>
    </command>

    <attribute code="0x0000" type="UNSIGNED_8_BIT_INTEGER" side="server" optional="false" writable="false" reportable="true">
        <name>Current Level</name>
        <description>The CurrentLevel attribute represents the current level of this device. The meaning of &apos;level&apos; is device dependent. Value is between 0 and 254.</description>
    </attribute>
    <attribute code="0x0001" type="UNSIGNED_16_BIT_INTEGER" side="server" optional="true" writable="false" reportable="false">
        <name>Remaining Time</name>
        <description>The RemainingTime attribute represents the time remaining until the current command is complete - it is specified in 1/10ths of a second.</description>
    </attribute>
    <attribute code="0x000F" type="BITMAP_8_BIT" side="server" optional="true" writable="false" reportable="false">
        <name>Options</name>
        <description></description>
    </attribute>
    <attribute code="0x0010" type="UNSIGNED_16_BIT_INTEGER" side="server" optional="true" writable="true" reportable="false">
        <name>On Off Transition Time</name>
        <description>The OnOffTransitionTime attribute represents the time taken to move to or from the target level when On of Off commands are received by an On/Off cluster on the same endpoint. It is specified in 1/10ths of a second.</description>
        <description>The actual time taken should be as close to OnOffTransitionTime as the device is able. N.B. If the device is not able to move at a variable rate, the OnOffTransitionTime attribute should not be implemented.</description>
    </attribute>
    <attribute code="0x0011" type="UNSIGNED_8_BIT_INTEGER" side="server" optional="true" writable="true" reportable="false">
        <name>On Level</name>
        <description>The OnLevel attribute determines the value that the CurrentLevel attribute is set to when the OnOff attribute of an On/Off cluster on the same endpoint is set to On. If the OnLevel attribute is not implemented, or is set to 0xff, it has no effect.</description>
    </attribute>
    <attribute code="0x0012" type="UNSIGNED_16_BIT_INTEGER" side="server" optional="true" writable="true" reportable="false">
        <name>On Transition Time</name>
        <description>The OnTransitionTime attribute represents the time taken to move the current level from the minimum level to the maximum level when an On command is received by an On/Off cluster on the same endpoint.  It is specified in 10ths of a second.  If this command is not implemented, or contains a value of 0xffff, the OnOffTransitionTime will be used instead.</description>
    </attribute>
    <attribute code="0x0013" type="UNSIGNED_16_BIT_INTEGER" side="server" optional="true" writable="true" reportable="false">
        <name>Off Transition Time</name>
        <description>The OffTransitionTime attribute represents the time taken to move the current level from the maximum level to the minimum level when an Off command is received by an On/Off cluster on the same endpoint.  It is specified in 10ths of a second.  If this command is not implemented, or contains a value of 0xffff, the OnOffTransitionTime will be used instead.</description>
    </attribute>
    <attribute code="0x0014" type="UNSIGNED_16_BIT_INTEGER" side="server" optional="true" writable="true" reportable="false">
        <name>Default Move Rate</name>
        <description>The DefaultMoveRate attribute determines the movement rate, in units per second, when a Move command is received with a Rate parameter of 0xFF.</description>
    </attribute>
    <attribute code="0x4000" type="UNSIGNED_8_BIT_INTEGER" side="server" optional="true" writable="true" reportable="false">
        <name>Start Up Current Level</name>
        <description></description>
    </attribute>

</cluster>

=== zsmartsystems/com.zsmartsystems.zigbee/com.zsmartsystems.zigbee/src/main/xml/zcl/0202_FanControl.xml
<cluster xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="zigbee-description.xsd" code="0x0202">
    <name>Fan Control</name>
    <description>This cluster specifies an interface to control the speed of a fan as part of a heating / cooling system.</description>
    <attribute code="0x0000" type="ENUMERATION_8_BIT" side="server" optional="true" writable="true" reportable="true" default="0x05">
        <name>Fan Mode</name>
        <description>The FanMode attribute is an 8-bit value that specifies the current speed of the fan.</description>
    </attribute>
    <attribute code="0x0001" type="ENUMERATION_8_BIT" side="server" optional="true" writable="true" reportable="true" default="0x02">
        <name>Fan Mode Sequence</name>
        <description>The FanModeSequence attribute is an 8-bit value that specifies the possible fan speeds that the thermostat can set.</description>
    </attribute>

</cluster>
